### PR TITLE
Update Dockerfile with ruby:3.3.4-alpine3.20

### LINKED ISSUE #142: GHPAGES-DOCKER needs to be updated - ruby gem
GitHub Pages is now using **v3.3.4** of Ruby. You are using **v2.7**. Please refer to the [ghpages-docker Wiki](https://github.com/hackforla/ghpages-docker/wiki#how-do-you-update-ghpages-docker) for instructions on how to update.

### PR DESCRIPTION
**Pull request by roslynwythe**
# fixes https://github.com/hackforla/ops/issues/142

Changes 
- updated ruby version from ruby:2.7.4-alpine3.14 to ruby:3.3.4-alpine3.20 in BUILD 1 and BUILD 2, following the instructions in **https://github.com/hackforla/ghpages-docker/wiki#how-do-you-update-ghpages-docker**

### CODE REVIEW

**Review by fyliu — APPROVED** [review]
Thanks for updating the docker image!

1. I was able to build and confirm that the new image works just as well as the old one as far as I can tell.

    ```bash
    # build the image with the existing <repo>/<name> but with a 
    # testing tag
    docker build -t hackforlaops/ghpages:testing .
    ```

1. I can confirm that the ruby version and the github-pages gem version are both updated.

    ```bash
    docker run -it hackforlaops/ghpages:testing sh

    # inside the container
    # check ruby version
    ruby --version

    # output
    ruby 3.3.4 ...

    # check gem version
    gem list | grep github-pages

    # output
    github-pages (232)
    ...
    ```

**Comment by fyliu** [comment]
@roslynwythe

I don't remember how, but I actually have write permission on this repo and can merge it. How would you like to merge? My own preference is "rebase and merge" to keep a linear history. No need to squash since your changes are clean and small already.

I recommend creating a personal docker hub account for testing. I didn't until I had to work on one of these docker image projects. Here's some [random docker hub notes](https://hackforla.github.io/docker-mkdocs/dockerhub/) I made while working on a similar project in case they're useful. The token and password are interchangeable in the cli when it prompts for `password`, but for gha I think it's more secure to store the token as a secret since that can be revoked if it's ever leaked.

I'm not actually part of the ops team so I'm just speaking for myself.

**Comment by roslynwythe** [comment]
Hi @fyliu for testing the new image locally I have created a branch off gh-pages and updated `docker-compose.yml` to pull the image `hackforlaops/ghpages:testing`.  See https://github.com/hackforla/website/pull/7359.  Please advise, for testing, should `container_name` remain with its current value `hfla_site` or should I define a new container name?  In what other containers or scripts do we reference `container_name`?

**Comment by fyliu** [comment]
Hi @roslynwythe. I don't think you need to create a `website` repo branch for testing, but you could. Just leave the `container_name` if it doesn't cause a conflict.

Generally, I think `container_name` is just unnecessary for projects using docker-compose. I did a quick search for "hfla_site" in the `website` project repository and didn't find any code or documentation that uses that container name. Looks like the project is only doing the normal thing of calling `docker-compose up`. The person who made the docker-compose.yml file probably followed a guide that told them to have it. But, it doesn't hurt anything, just not needed.

**Comment by roslynwythe** [comment]
Thank you @fyliu for that information.  I created a [branch](https://github.com/hackforla/website/pull/7359) for testing and it looks like everything is working fine.  But it appears that merging this PR will not trigger `.github/workflows/build-and-push-to-docker-hub.yml` so how does the team actually initiate that workflow?

**Comment by fyliu** [comment]
@roslynwythe I think merging this PR should create a `push` event to trigger `.github/workflows/build-and-push-to-docker-hub.yml`.
I can test it in my fork which pushes to my personal docker hub repo.

Were you working on another workflow file to push a testing image on PR approval? I remember looking up how to do that but 

### helpful commands

I didn't find these commands in the wiki documentation but I want to add them somewhere

For images:

```console
# build testing image
docker build . -t hackforlaops/ghpages:testing
# shell into a new container from image and remove container on exit
docker run --rm -it hackforlaops/ghpages:testing sh
```

For alpine package management (in an alpine container):

```console
# update package information
apk update

# installed package version
apk list -I openssl
# available package version
apk info openssl

# install/upgrade package
apk add openssl
# remove package
apk del openssl
```

### `openssl` vulnerability

From Docker Desktop, I also see an `openssl` vulnerability that was fixed 2 days ago. I'm not sure if that's something to be fixed in this issue. To update the version, add `openssl` to the list here
https://github.com/hackforla/ghpages-docker/blob/9c91768028df219c3979d02d3516078fa2cf03de/Dockerfile#L96-L101

or to remove it: `apk del openssl` around the same place in the `Dockerfile`.

I'm not sure if the website will still work okay without it since it's not copied over from the `build` stage. The `build` stage installs `libressl`, which something might be using or not. `libressl` adoption seems to have gone down since 2020, so there might not be something that requires it anymore. I removed `libressl` and the `openssl` from the base image in all build stages and the build went through and runs fine locally. But I'm not using ssl.

**Comment by fyliu** [comment]
@roslynwythe I attended the ops meeting and they didn't have anything to add, so they asked me to merge this. Thank you for updating the docker image!

**Comment by fyliu** [comment]
@roslynwythe hmm... the build and push actions are failing. Bad Credentials for GitHub?

I'm on a cellphone and it's hard to go get the message to paste here.

**Comment by fyliu** [comment]
@roslynwythe It looks like the PAT for the Daniel Ridge bot may have expired or rotated without updating the secret in this repo. I filed an issue for Ops to look at it.
- #4

**Pull request merged**
